__author__ = 'moskupols'


class ExplanationSource:

    def __init__(self, name: str):
        self._name = name

    def explain(self, word: str)->list:
        """
        Returns list of explanation.Explanation for the given word.

        >>> from explanations import sources_registry
        >>> s = sources_registry.source_for_name('PhraseologicalSource')
        >>> list(map(str, s.explain('голод')))
        ['*пропуск* не тетка']
        >>> list(map(str, s.explain('полка')))
        ['класть зубы на *пропуск*', 'положить зубы на *пропуск*']

        >>> s = sources_registry.source_for_name('CollocationsSource')
        >>> list(map(str, s.explain('учёт')))
        ['миграционный *пропуск*']
        >>> list(map(str, s.explain('язык')))
        ['русский *пропуск*']

        >>> s = sources_registry.source_for_name('AntonymSource')
        >>> list(map(str, s.explain('свет')))
        ['антоним к словам тьма, мрак, темнота, тень']
        >>> list(map(str, s.explain('альтруист')))
        ['антоним к слову эгоист']
        >>> list(map(str, s.explain('диван')))
        []

        >>> s = sources_registry.source_for_name('SynonymSource')
        >>> list(map(str, s.explain('богомолье')))
        ['синоним к словам богослужение, священнодействие']
        >>> list(map(str, s.explain('адский')))
        []

        :param word: russian noun in the initial form, in lowercase.
        :return: list of Explanation objects
        """
        from explanations.explanation import Explanation
        return [Explanation(self, key) for key in self.keys_for_word(word)]

    @property
    def name(self)->str:
        return self._name

    def text_for_key(self, key):
        """
        This method is used by explanation.Explanation to represent its information stored in key.
        If not overridden, returns repr(key).

        :param key: key generated by keys_for_word
        :return: string containing end user representation of the explanation
        """
        return repr(key)

    def keys_for_word(self, word: str):
        """
        This method is used by explain to initialize Explanations list. It should return a list of
        keys objects. Each of them has to be enough for text_for_key to make the explanation text.

        :param word: the russian lowercase word to be explained
        :raise NotImplementedError: if not overridden by successors.
        """
        raise NotImplementedError

    def explainable_words(self):
        """
        Generates all words explainable using this source. Should be overridden by successors.
        :return: Iterable of explainable words
        :raise NotImplementedError: if not overridden by successors.
        """
        raise NotImplementedError
